name: Build and Publish Docker Container

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Use Docker Token
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p $DOCKER_TOKEN
          # Assurez-vous que le nom du répertoire est en minuscules
          docker build -t ghcr.io/${{ github.repository }}/monprojetdocker:latest .
          docker push ghcr.io/${{ github.repository }}/monprojetdocker:latest

