name: Build and Publish Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Use Docker Token
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p $DOCKER_TOKEN
          docker build -t ghcr.io/${{ github.repository }}/ue19_labo09-10:latest .
          docker push ghcr.io/${{ github.repository }}/ue19_labo09-10:latest

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/ue19_labo09-10:latest
              



              
  

